### PR TITLE
Internal networks

### PR DESCRIPTION
**Pull request by geekbass**
This is to add a feature for multi region that allows for other "internal_network" range to be added to the internal SG. This is an attempt to use this to prevent a breaking change with the VPC Peering module.

### CODE REVIEW

**Comment by fatz** [comment]
@geekbass just reviewed this. So are you sure this works. IMO the rule will overwrite the inline rules as described in the docs of the resource like described in #5 

@bernadinm, @geekbass can we merge #7 and #5 to get the internal_networks var but the changes from #7

**Comment by geekbass** [comment]
> @geekbass just reviewed this. So are you sure this works. IMO the rule will overwrite the inline rules as described in the docs of the resource like described in #5
> 
@fatz Apologies, had not push latest commit. I have moved the additional group rule resource from the VPC peering module to SG as I believe this is where we should put such a resource. https://github.com/dcos-terraform/terraform-aws-vpc-peering/pull/6/commits/8ab5b8959be673ba45899ad2472eebb32deb82e8


The latest commit will allow users to specify and include ANY list of internal networks in additional to the AWS internal network (such as a "remote" region network). 

Was not able to find a way around this without introducing a breaking change as we discussed.

**Review by fatz — CHANGES_REQUESTED** [review]
i still think there will be a conflict with `aws_security_group.internal` as it has inline rules see https://www.terraform.io/docs/providers/aws/r/security_group_rule.html

IMO @bernadinm solved this in #5 by just deleting the inline rules. Think this should be merged with his proposal

**Comment by fatz** [comment]
@geekbass if you have time can we please get rid of the inline rules and replace them with the rule resource

**Review by fatz — APPROVED** [review]
lgtm

**Review by fatz — APPROVED** [review]
lgtm thx

**Review by bernadinm — APPROVED** [review]
LGTM

**Pull request merged**
